/-
Copyright (c) 2026 Paul Butcher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Postgres
import PostgresTest.Framework
import Plausible

open Postgres
open Postgres.Test
open Plausible

/--
Checks `p` over a generated sample of `α`, shrinking any counter-example to a minimal failing
case before reporting it.
-/
def checkProperty (α : Type) [Repr α] [Arbitrary α] [Shrinkable α]
    (p : α → Bool) (label : String) (cfg : Configuration := {}) : TestM Unit := do
  match ← Testable.checkIO (NamedBinder "x" (∀ x : α, p x)) cfg with
  | .success _ => recordSuccess s!"{label}: held across generated examples"
  | .gaveUp n => throw <| IO.userError s!"{label}: gave up after {n} attempts satisfying preconditions"
  | .failure _ xs n =>
    throw <| IO.userError (Testable.formatFailure s!"{label}: found a counter-example" xs n)

/--
Pads or truncates to the exactly 16 bytes a `uuid` requires, so that an arbitrary generated byte
array can stand in for one.
-/
def toUuidBytes (bs : Array UInt8) : Uuid :=
  ⟨⟨((bs.toList ++ List.replicate 16 0).take 16).toArray⟩⟩

/--
Round trip properties for the pure text codecs. These are properties rather than theorems
because each one bottoms out in `String`/`ByteArray` primitives (`String.push`, `String.drop`,
`splitOn`, `ByteArray.toList`) that the kernel will not reduce, so `decide` gets stuck on even a
single concrete input; a proof would instead have to be built by hand out of `String` lemmas, and
the `String.Pos` arithmetic underlying `drop`/`splitOn` puts that well beyond a time-boxed
attempt. The parts of these codecs that do reduce are proved outright in `Tests.Codecs`.
-/
def testCodecProperties : TestM Unit :=
  withHeader "=== Testing text codec round trips (property-based) ===" <| guardTest do
    checkProperty (Array UInt8)
      (fun bs => TextCodec.hexToByteArray? (TextCodec.byteArrayToHex ⟨bs⟩) == some ⟨bs⟩)
      "bytea hex"

    -- Quantified over bit patterns rather than `Float` directly: it is exactly the bits that
    -- `floatToText` claims to preserve, and generating them uniformly reaches the subnormals and
    -- extreme exponents that a `Float` generator built from small numerals never would.
    checkProperty UInt64
      (fun bits =>
        let f := Float.ofBits bits
        match TextCodec.floatOfText? (TextCodec.floatToText f) with
        | none => false
        -- NaN is excluded from the bit comparison because `floatToText` maps every NaN to the
        -- single token `NaN`, which cannot carry the original payload back.
        | some g => if f.isNaN then g.isNaN else g.toBits == bits)
      "float bit-exact"

    checkProperty (Bool × Nat × Nat)
      (fun (negative, unscaled, scale) =>
        let n := Numeric.ofDigits negative unscaled scale
        Numeric.ofText? n.toText == some n)
      "numeric text"

    checkProperty (Array UInt8)
      (fun bs => let u := toUuidBytes bs; Uuid.ofText? u.toText == some u)
      "uuid text"

    -- `maxSize := 300` so generated element strings reliably grow past the lengths at which
    -- quoting and escaping start to interact.
    checkProperty (List (Option String))
      (fun elems => parseArrayLiteral? (arrayLiteralOf elems) == some elems)
      "array literal" { maxSize := 300 }

    -- An `Error` thrown as an `IO.Error` is recovered intact by `ofIOError?`, whatever its message
    -- and constraint name contain. Plausible's default characters omit `%` and `]` and are almost
    -- always ASCII, so both are drawn mostly from the characters the prefix encoding must handle.
    -- The SQLSTATE is kept alphanumeric, as real ones are, since a `;` or `]` in it would be
    -- misparsed by design. A theorem would have to live beside `Error`'s private helpers, and
    -- would still have to reason about `splitOn`, for which core has no lemmas.
    letI : Arbitrary Char := Char.arbitraryFromList 3 "%;]= [a\n\té€".toList (by decide)
    checkProperty (String × List Char × Option (List Char))
      (fun (sqlstate, message, constraint) =>
        let e : Error :=
          { sqlstate := sqlstate.toList.filter Char.isAlphanum |> String.ofList
            message := String.ofList message
            constraint := String.ofList <$> constraint }
        Error.ofIOError? (.userError (toString e)) == some e)
      "error prefix"
